[package]
name = "sruja-agent"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
sruja-diagnostics = { path = "../sruja-diagnostics" }
sruja-graph = { path = "../sruja-graph" }
sruja-language = { path = "../sruja-language" }
fs2 = "0.4.3"

[dev-dependencies]
tempfile = "3.10"
