name: 'Setup Node.js'
description: 'Setup Node.js with npm caching and dependency installation'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'
  install-deps:
    description: 'Whether to install npm dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: npm ci

