[package]
name = "sruja-diff"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sruja-language = { path = "../sruja-language" }
sruja-scan = { path = "../sruja-scan" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
