# Codacy Configuration
# This file configures code quality rules and patterns to ignore

# Ignore complexity warnings for specific files
# These functions handle complex but necessary logic:
# - sanitizeUrl: Security validation requires multiple protocol/path checks
# - handleRun: UI interaction handler with multiple validation/error paths
# - updateToolbar: Sticky toolbar logic with visibility and positioning calculations
# - processCompileOutput: Multi-format processor (SVG/HTML/Image) requires branching

# Pattern to ignore: Lizard cyclomatic complexity warnings
# These are acceptable because complexity is intentional for the use cases above

exclude_paths:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/public/**"

# For Codacy MCP CLI analysis, these warnings are documented but not blocking
# See learn/COMPLEXITY_WARNINGS.md for detailed explanations

