# Sruja Architecture Context

This file is auto-generated by `sruja ai-context -r . -f cursor-rules`

## Architecture Overview

- Modules: 2026
- Services: 0
- Databases: 1
- External APIs: 0

## Layers

### MODELS (28 modules)
No external dependencies allowed.

### OTHER (1939 modules)
No external dependencies allowed.

### UTILS (59 modules)
No external dependencies allowed.

## Boundary Rules

- **ui -> data**: UI should not directly access data layer - use services

## Forbidden Patterns

- Avoid direct database access from routes/handlers - use a service layer
- Do not import internal modules from other services directly
- UI components should not directly call database layers

## Architecture retrieval (MCP)

MCP: `sruja_list_architecture_index` → `sruja_get_topology` → `sruja_get_elements` → `sruja_get_task_context` (`cache_friendly` optional).
Compact brief: `llms-architecture.txt`. Full DSL only via MCP `sruja://architecture/main`.

## When suggesting code

1. Respect layer boundaries - check imports before suggesting
2. Use existing patterns in the codebase
3. If adding a new dependency, verify it does not violate boundaries
4. Run `sruja drift -r .` after changes to verify architecture health

## Agentic Optimization Loop

When making architectural changes, you MUST follow this loop:
1. Run `sruja_evaluate_proposal` to validate the health of your changes.
2. If it fails, run `sruja_record_learning` to document the failed hypothesis and update your approach.
3. Only present the final code to the user after achieving a successful evaluation.


## Multi-Repo System Context

Composed architecture from **4 repositories**.
Index source: `./system.index.json`


# Global AI Agent Guidelines
You MUST read and strictly adhere to the instructions located in `AGENTS.md` before proceeding with any task.
