version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - ineffassign # Detect ineffectual assignments
    - noctx
    - prealloc
    - revive
    - staticcheck # Additional static analysis
    - unparam
  disable:
    - funlen
    - goconst
    - gocyclo
  settings:
    funlen:
      lines: 120
      statements: 80
    gocyclo:
      min-complexity: 25
    revive:
      rules:
        - name: unused-parameter
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - goconst
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules
      - apps/
      - packages/
run:
  timeout: 5m
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules
      - apps/
      - packages/
