run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosec
    - errcheck
    - ineffassign
    - revive
    - unparam
  disable:
    - funlen
    - gocyclo
    - goconst
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 25
  funlen:
    lines: 120
    statements: 80
  revive:
    rules:
      - name: unused-parameter
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck
        - gosec
