version: 2
project_name: sruja

before:
  hooks:
    - go mod tidy

builds:
  - id: sruja
    main: ./cmd/sruja
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.BuildDate={{ .Date }} -X main.GitCommit={{ .Commit }}

archives:
  - id: default
    ids:
      - sruja
    formats: ["tar.gz"]
    name_template: '{{ .ProjectName }}_{{ .Os | title }}_{{- if eq .Arch "amd64" -}}x86_64{{- else -}}{{ .Arch }}{{- end -}}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  draft: false
  prerelease: auto
