[package]
name = "sruja-extract"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sruja-language = { path = "../sruja-language" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = "0.4"
ignore = "0.4"

[dev-dependencies]
tempfile = "3.16"
