[package]
name = "sruja-language"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Parser and AST implementation for Sruja DSL"

[dependencies]
sruja-diagnostics = { path = "../sruja-diagnostics" }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
nom = { version = "7", features = ["std"] }
