use std::collections::{HashMap, HashSet};
use std::path::Path;

use super::types::*;
use sruja_scan::{graph::compute_all_centrality, Graph, NodeKind};

pub fn format_cursor_rules_multi(context: &MultiRepoArchitectureContext) -> String {
    let mut out = String::new();
    out.push_str("# Sruja Architecture Context (Multi-Repo)\n\n");
    out.push_str("This file is auto-generated by `sruja context -f cursor-rules -r <repo>...`\n\n");
    out.push_str("## Combined Summary\n\n");
    out.push_str(&format!(
        "- Repos: {}\n- Modules: {}\n- Services: {}\n- Databases: {}\n- External APIs: {}\n\n",
        context.repos.len(),
        context.combined_summary.total_modules,
        context.combined_summary.total_services,
        context.combined_summary.total_databases,
        context.combined_summary.total_external_apis
    ));

    if !context.cross_repo_rules.is_empty() {
        out.push_str("## Cross-Repo Rules\n\n");
        for rule in &context.cross_repo_rules {
            out.push_str(&format!("- {}\n", rule));
        }
        out.push('\n');
    }

    for repo in &context.repos {
        out.push_str("## Repo\n\n");
        out.push_str(&format!("- Path: {}\n\n", repo.repo));
        out.push_str(&format_cursor_rules(repo));
        out.push_str("\n---\n\n");
    }

    out
}

pub fn format_copilot_instructions_multi(context: &MultiRepoArchitectureContext) -> String {
    let mut out = String::new();
    out.push_str("# Architecture Context for GitHub Copilot (Multi-Repo)\n\n");
    out.push_str("Generated by `sruja context -f copilot-instructions -r <repo>...`\n\n");
    out.push_str("## Combined Summary\n\n");
    out.push_str(&format!(
        "Repos: {}. Total modules: {}. Total services: {}. Total databases: {}.\n\n",
        context.repos.len(),
        context.combined_summary.total_modules,
        context.combined_summary.total_services,
        context.combined_summary.total_databases
    ));

    if !context.cross_repo_rules.is_empty() {
        out.push_str("## Cross-Repo Rules\n\n");
        for rule in &context.cross_repo_rules {
            out.push_str(&format!("- {}\n", rule));
        }
        out.push('\n');
    }

    for repo in &context.repos {
        out.push_str("## Repo\n\n");
        out.push_str(&format!("Path: {}\n\n", repo.repo));
        out.push_str(&format_copilot_instructions(repo));
        out.push_str("\n---\n\n");
    }

    out
}

pub fn format_markdown_multi(context: &MultiRepoArchitectureContext) -> String {
    let mut out = String::new();
    let mut budget = TokenBudget::new(10000);

    budget.push_str(&mut out, "# Architecture Context (Multi-Repo)\n\n");
    budget.push_str(&mut out, "| Type | Count |\n|------|-------|\n");
    budget.push_str(&mut out, &format!("| Repos | {} |\n", context.repos.len()));
    budget.push_str(
        &mut out,
        &format!("| Modules | {} |\n", context.combined_summary.total_modules),
    );
    budget.push_str(
        &mut out,
        &format!(
            "| Services | {} |\n",
            context.combined_summary.total_services
        ),
    );
    budget.push_str(
        &mut out,
        &format!(
            "| Databases | {} |\n",
            context.combined_summary.total_databases
        ),
    );
    budget.push_str(
        &mut out,
        &format!(
            "| External APIs | {} |\n\n",
            context.combined_summary.total_external_apis
        ),
    );

    if !context.cross_repo_rules.is_empty() {
        budget.push_str(&mut out, "## Cross-Repo Rules\n\n");
        for rule in &context.cross_repo_rules {
            budget.push_str(&mut out, &format!("- {}\n", rule));
        }
        budget.push_str(&mut out, "\n");
    }

    for repo in &context.repos {
        budget.push_str(&mut out, "---\n\n");
        budget.push_str(&mut out, &format_markdown(repo));
    }

    budget.finish(&mut out);
    out
}

pub fn format_cursor_rules(context: &ArchitectureContext) -> String {
    let mut out = String::new();
    let mut budget = TokenBudget::new(context.max_tokens);

    budget.push_str(&mut out, "# Sruja Architecture Context\n\n");
    budget.push_str(
        &mut out,
        &format!(
            "This file is auto-generated by `sruja context -r {} -f cursor-rules`\n\n",
            context.repo
        ),
    );
    budget.push_str(&mut out, "## Architecture Overview\n\n");
    budget.push_str(
        &mut out,
        &format!(
            "- Modules: {}\n- Services: {}\n- Databases: {}\n- External APIs: {}\n\n",
            context.summary.total_modules,
            context.summary.total_services,
            context.summary.total_databases,
            context.summary.total_external_apis
        ),
    );

    if !context.layers.is_empty() {
        budget.push_str(&mut out, "## Layers\n\n");
        for layer in &context.layers {
            budget.push_str(
                &mut out,
                &format!(
                    "### {} ({} modules)\n",
                    layer.name.to_uppercase().replace("_", " "),
                    layer.modules
                ),
            );
            if !layer.can_depend_on.is_empty() {
                budget.push_str(
                    &mut out,
                    &format!("Can depend on: {}\n\n", layer.can_depend_on.join(", ")),
                );
            } else {
                budget.push_str(&mut out, "No external dependencies allowed.\n\n");
            }
        }
    }

    if !context.boundaries.is_empty() {
        budget.push_str(&mut out, "## Boundary Rules\n\n");
        for boundary in &context.boundaries {
            if !boundary.allowed {
                budget.push_str(
                    &mut out,
                    &format!(
                        "- **{} -> {}**: {}\n",
                        boundary.from, boundary.to, boundary.reason
                    ),
                );
            }
        }
        budget.push_str(&mut out, "\n");
    }

    if !context.forbidden_patterns.is_empty() {
        budget.push_str(&mut out, "## Forbidden Patterns\n\n");
        for pattern in &context.forbidden_patterns {
            budget.push_str(&mut out, &format!("- {}\n", pattern));
        }
        budget.push_str(&mut out, "\n");
    }

    if !context.active_decisions.is_empty() {
        budget.push_str(&mut out, "## Active Architecture Decisions (ADRs)\n\n");
        for decision in &context.active_decisions {
            budget.push_str(&mut out, &format!("- {}\n", decision));
        }
        budget.push_str(&mut out, "\n");
    }

    budget.push_str(&mut out, "## When suggesting code\n\n");
    budget.push_str(
        &mut out,
        "1. Respect layer boundaries - check imports before suggesting\n",
    );
    budget.push_str(&mut out, "2. Use existing patterns in the codebase\n");
    budget.push_str(
        &mut out,
        "3. If adding a new dependency, verify it does not violate boundaries\n",
    );
    budget.push_str(
        &mut out,
        "4. Run `sruja drift -r .` after changes to verify architecture health\n",
    );

    if let Some(focus) = &context.focus {
        budget.push_str(&mut out, "\n## Current Task Focus\n\n");
        budget.push_str(&mut out, &format!("- File: {}\n", focus.file));
        if let Some(intent) = &focus.intent {
            budget.push_str(&mut out, &format!("- Intent: {}\n", intent));
        }
        if let Some(br) = &focus.blast_radius {
            budget.push_str(
                &mut out,
                &format!(
                    "- Blast radius: {} upstream, {} downstream (depth {})\n",
                    br.upstream.len(),
                    br.downstream.len(),
                    focus.depth
                ),
            );
        }
    }

    if let Some(system) = &context.system_context {
        budget.push_str(&mut out, &format_system_context_markdown(system));
    }

    budget.finish(&mut out);
    out
}

pub fn format_copilot_instructions(context: &ArchitectureContext) -> String {
    let mut out = String::new();
    let mut budget = TokenBudget::new(context.max_tokens);

    budget.push_str(&mut out, "# Architecture Context for GitHub Copilot\n\n");
    budget.push_str(
        &mut out,
        &format!(
            "Generated by `sruja context -r {} -f copilot-instructions`\n\n",
            context.repo
        ),
    );

    budget.push_str(&mut out, "## Summary\n");
    budget.push_str(
        &mut out,
        &format!(
            "This codebase has {} modules, {} services, {} databases.\n\n",
            context.summary.total_modules,
            context.summary.total_services,
            context.summary.total_databases
        ),
    );

    budget.push_str(&mut out, "## Key Rules\n\n");
    budget.push_str(&mut out, "1. **Respect layers**: ");
    if !context.layers.is_empty() {
        let layer_names: Vec<_> = context.layers.iter().map(|l| l.name.clone()).collect();
        budget.push_str(
            &mut out,
            &format!("Layers found: {}\n", layer_names.join(", ")),
        );
    } else {
        budget.push_str(&mut out, "No layers detected.\n");
    }

    budget.push_str(
        &mut out,
        "2. **No cross-service imports**: Services should communicate via API/event\n",
    );
    budget.push_str(
        &mut out,
        "3. **UI -> Services -> Data**: Follow this flow, never skip layers\n\n",
    );

    if !context.boundaries.is_empty() {
        budget.push_str(&mut out, "## Forbidden Dependencies\n");
        for boundary in context.boundaries.iter().filter(|b| !b.allowed).take(10) {
            budget.push_str(
                &mut out,
                &format!("- {} -> {} is not allowed\n", boundary.from, boundary.to),
            );
        }
        budget.push_str(&mut out, "\n");
    }

    if !context.active_decisions.is_empty() {
        budget.push_str(&mut out, "## Active Architecture Decisions (ADRs)\n");
        for decision in &context.active_decisions {
            budget.push_str(&mut out, &format!("- {}\n", decision));
        }
        budget.push_str(&mut out, "\n");
    }

    budget.push_str(&mut out, "## Before Committing\n");
    budget.push_str(
        &mut out,
        "Run: `sruja drift -r .` to check for architectural violations.\n",
    );

    if let Some(focus) = &context.focus {
        budget.push_str(&mut out, "\n## Current Task Focus\n\n");
        budget.push_str(&mut out, &format!("- File: {}\n", focus.file));
        if let Some(intent) = &focus.intent {
            budget.push_str(&mut out, &format!("- Intent: {}\n", intent));
        }
    }

    if let Some(system) = &context.system_context {
        budget.push_str(&mut out, &format_system_context_markdown(system));
    }

    budget.finish(&mut out);
    out
}

pub fn format_markdown(context: &ArchitectureContext) -> String {
    let mut out = String::new();
    let mut budget = TokenBudget::new(context.max_tokens);

    budget.push_str(&mut out, "# Architecture Context\n\n");
    budget.push_str(
        &mut out,
        &format!(
            "> Generated by `sruja context -r {} -f markdown` for {}\n\n",
            context.repo, context.repo
        ),
    );

    budget.push_str(&mut out, "## Overview\n\n");
    budget.push_str(&mut out, "| Type | Count |\n|------|-------|\n");
    budget.push_str(
        &mut out,
        &format!("| Modules | {} |\n", context.summary.total_modules),
    );
    budget.push_str(
        &mut out,
        &format!("| Services | {} |\n", context.summary.total_services),
    );
    budget.push_str(
        &mut out,
        &format!("| Databases | {} |\n", context.summary.total_databases),
    );
    budget.push_str(
        &mut out,
        &format!(
            "| External APIs | {} |\n\n",
            context.summary.total_external_apis
        ),
    );

    if !context.layers.is_empty() {
        budget.push_str(&mut out, "## Layers\n\n");
        for layer in &context.layers {
            budget.push_str(
                &mut out,
                &format!(
                    "### {}\n\n**Can depend on:** {}\n\n**Modules:** {}\n\n",
                    layer.name,
                    if layer.can_depend_on.is_empty() {
                        "None".to_string()
                    } else {
                        layer.can_depend_on.join(", ")
                    },
                    layer.modules
                ),
            );
        }
    }

    if !context.forbidden_patterns.is_empty() {
        budget.push_str(&mut out, "## Rules to Follow\n\n");
        for pattern in &context.forbidden_patterns {
            budget.push_str(&mut out, &format!("- {}\n", pattern));
        }
        budget.push_str(&mut out, "\n");
    }

    if !context.active_decisions.is_empty() {
        budget.push_str(&mut out, "## Active Architecture Decisions (ADRs)\n\n");
        for decision in &context.active_decisions {
            budget.push_str(&mut out, &format!("- {}\n", decision));
        }
        budget.push_str(&mut out, "\n");
    }

    if let Some(focus) = &context.focus {
        budget.push_str(&mut out, "## Current Task Focus\n\n");
        budget.push_str(&mut out, &format!("- File: {}\n", focus.file));
        if let Some(intent) = &focus.intent {
            budget.push_str(&mut out, &format!("- Intent: {}\n", intent));
        }
        if let Some(br) = &focus.blast_radius {
            budget.push_str(
                &mut out,
                &format!(
                    "- Blast radius: {} upstream, {} downstream (depth {})\n",
                    br.upstream.len(),
                    br.downstream.len(),
                    focus.depth
                ),
            );
        }
    }

    if let Some(system) = &context.system_context {
        budget.push_str(&mut out, &format_system_context_markdown(system));
    }

    budget.finish(&mut out);
    out
}

pub fn format_repomap(context: &ArchitectureContext, graph: &Graph) -> String {
    let mut out = String::new();
    let mut budget = TokenBudget::new(context.max_tokens);

    budget.push_str(&mut out, "# Sruja Repomap\n\n");
    budget.push_str(&mut out, &format!("Repo: {}\n", context.repo));
    budget.push_str(&mut out, &format!("Nodes: {}\n", graph.nodes.len()));
    budget.push_str(&mut out, &format!("Edges: {}\n", graph.edges.len()));

    let scores = compute_all_centrality(graph);
    let node_by_id: HashMap<&str, &sruja_scan::Node> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    let mut outgoing: HashMap<&str, HashSet<&str>> = HashMap::new();
    let mut incoming: HashMap<&str, HashSet<&str>> = HashMap::new();
    for e in &graph.edges {
        let src = e.source.as_str();
        let tgt = e.target.as_str();
        if src == tgt {
            continue;
        }
        outgoing.entry(src).or_default().insert(tgt);
        incoming.entry(tgt).or_default().insert(src);
    }

    let repo_root = Path::new(&context.repo);
    let repo_prefix = repo_root
        .canonicalize()
        .ok()
        .and_then(|p| p.to_str().map(|s| s.replace('\\', "/")));

    budget.push_str(&mut out, "\n## Top Nodes\n\n");

    let mut ranked: Vec<(&sruja_scan::Node, f64)> = graph
        .nodes
        .iter()
        .filter(|n| !n.id.contains('#'))
        .map(|n| {
            let pr = scores.get(&n.id).map(|s| s.pagerank).unwrap_or(0.0_f64);
            (n, pr)
        })
        .collect();

    ranked.sort_by(|left, right| {
        let (a, ap) = left;
        let (b, bp) = right;
        bp.partial_cmp(ap)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.id.cmp(&b.id))
    });

    let top_limit = 50usize;
    for (n, pr) in ranked
        .into_iter()
        .filter(|(n, _)| {
            matches!(
                n.kind,
                NodeKind::Service | NodeKind::Database | NodeKind::ExternalApi | NodeKind::Module
            )
        })
        .take(top_limit)
    {
        let kind = repomap_kind(n.kind);
        let path = n
            .path
            .as_deref()
            .and_then(|p| repomap_relative_path(p, repo_prefix.as_deref()));

        let mut line = if let Some(p) = &path {
            format!("- {}: {} ({})", kind, n.label, p)
        } else {
            format!("- {}: {}", kind, n.label)
        };

        if let Some(owner) = &n.owner {
            line.push_str(&format!(" [owner={}]", owner));
        }
        if let Some(crit) = &n.criticality {
            line.push_str(&format!(" [criticality={:?}]", crit));
        }
        line.push_str(&format!(" [pr={:.3}]\n", pr));

        if !budget.push_str(&mut out, &line) {
            break;
        }

        let deps = outgoing
            .get(n.id.as_str())
            .map(|s| repomap_top_neighbors(s, &node_by_id, &scores, 5))
            .unwrap_or_default();
        if !deps.is_empty() {
            budget.push_str(&mut out, &format!("  deps: {}\n", deps.join(", ")));
        }

        let used_by = incoming
            .get(n.id.as_str())
            .map(|s| repomap_top_neighbors(s, &node_by_id, &scores, 5))
            .unwrap_or_default();
        if !used_by.is_empty() {
            budget.push_str(&mut out, &format!("  used_by: {}\n", used_by.join(", ")));
        }
    }

    if let Some(focus) = &context.focus {
        budget.push_str(&mut out, "\n## Focus\n\n");
        budget.push_str(&mut out, &format!("- File: {}\n", focus.file));
        if let Some(intent) = &focus.intent {
            budget.push_str(&mut out, &format!("- Intent: {}\n", intent));
        }
        budget.push_str(&mut out, &format!("- Depth: {}\n", focus.depth));

        if !focus.matched_nodes.is_empty() {
            budget.push_str(&mut out, "\nMatched nodes:\n");
            for n in &focus.matched_nodes {
                let path = n
                    .path
                    .as_deref()
                    .and_then(|p| repomap_relative_path(p, repo_prefix.as_deref()));
                let mut line = if let Some(p) = path {
                    format!("- {}: {} ({})", repomap_kind(n.kind), n.label, p)
                } else {
                    format!("- {}: {}", repomap_kind(n.kind), n.label)
                };

                if let Some(owner) = &n.owner {
                    line.push_str(&format!(" [owner={}]", owner));
                }
                if let Some(crit) = &n.criticality {
                    line.push_str(&format!(" [criticality={:?}]", crit));
                }
                line.push('\n');
                budget.push_str(&mut out, &line);
            }
        }
    }

    if let Some(system) = &context.system_context {
        budget.push_str(&mut out, "\n## System Context\n\n");
        budget.push_str(&mut out, &format!("Index: {}\n", system.index_path));
        budget.push_str(&mut out, &format!("Repos: {}\n", system.total_repos));
        for el in &system.cross_repo_elements {
            budget.push_str(
                &mut out,
                &format!("- {} ({}): owned by {}\n", el.label, el.kind, el.repo_id),
            );
        }
    }

    budget.finish(&mut out);
    out
}

pub fn format_system_context_markdown(ctx: &SystemContext) -> String {
    let mut md = String::new();
    md.push_str("\n## Multi-Repo System Context\n\n");
    md.push_str(&format!(
        "Composed architecture from **{} repositories**.\n",
        ctx.total_repos
    ));
    md.push_str(&format!("Index source: `{}`\n\n", ctx.index_path));

    if !ctx.cross_repo_elements.is_empty() {
        md.push_str("### Cross-Repo Dependencies\n\n");
        for el in &ctx.cross_repo_elements {
            let mut line = format!("- **{}** ({} in `{}`)", el.label, el.kind, el.repo_id);
            if let Some(owner) = &el.owner {
                line.push_str(&format!(" [owner={}]", owner));
            }
            if let Some(crit) = &el.criticality {
                line.push_str(&format!(" [criticality={:?}]", crit));
            }
            line.push('\n');
            md.push_str(&line);
        }
        md.push('\n');
    }

    if !ctx.cross_repo_edges.is_empty() {
        md.push_str("### Key Relationships\n\n");
        for edge in &ctx.cross_repo_edges {
            md.push_str(&format!(
                "- `{}` -> `{}` {}\n",
                edge.source,
                edge.target,
                edge.label.as_deref().unwrap_or("")
            ));
        }
        md.push('\n');
    }

    if !ctx.conflicts.is_empty() {
        md.push_str("### ⚠ Architectural Conflicts\n\n");
        for c in &ctx.conflicts {
            md.push_str(&format!("- {}\n", c));
        }
        md.push('\n');
    }

    md
}

fn repomap_kind(kind: NodeKind) -> &'static str {
    match kind {
        NodeKind::Service => "service",
        NodeKind::Database => "database",
        NodeKind::ExternalApi => "external_api",
        NodeKind::Module => "module",
        _ => "node",
    }
}

fn repomap_relative_path(path: &str, repo_prefix: Option<&str>) -> Option<String> {
    let normalized = path.replace('\\', "/");
    let rel = if let Some(prefix) = repo_prefix {
        let prefix = prefix.trim_end_matches('/');
        normalized
            .strip_prefix(prefix)
            .unwrap_or(normalized.as_str())
            .trim_start_matches('/')
            .to_string()
    } else {
        normalized
            .trim_start_matches("./")
            .trim_start_matches('/')
            .to_string()
    };
    if rel.is_empty() {
        None
    } else {
        Some(rel)
    }
}

fn repomap_top_neighbors(
    neighbors: &HashSet<&str>,
    node_by_id: &HashMap<&str, &sruja_scan::Node>,
    scores: &HashMap<String, sruja_scan::graph::ComponentImportance>,
    limit: usize,
) -> Vec<String> {
    let mut v: Vec<(&str, f64, &str)> = neighbors
        .iter()
        .filter_map(|id| {
            let n = node_by_id.get(id)?;
            let pr = scores.get(n.id.as_str()).map(|s| s.pagerank).unwrap_or(0.0);
            Some((n.label.as_str(), pr, n.id.as_str()))
        })
        .collect();

    v.sort_by(|a, b| {
        b.1.partial_cmp(&a.1)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.2.cmp(b.2))
    });

    v.into_iter()
        .take(limit)
        .map(|(label, _, _)| label.to_string())
        .collect()
}
