[package]
name = "sruja-watch"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "File watcher for repo change detection"

[dependencies]
notify = "6"
notify-debouncer-mini = "0.4"
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"
