name: "Setup Go"
description: "Setup Go with caching and dependency installation"
inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.25.5"
  install-deps:
    description: "Whether to install Go dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache Go modules
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
      continue-on-error: true
      id: go-cache

    - name: Clean Go cache on restore failure
      if: always() && steps.go-cache.outcome == 'failure'
      shell: bash
      run: |
        # Clean up any corrupted cache directories that might cause issues
        echo "⚠️  Go cache restore failed, cleaning up potentially corrupted cache..."
        rm -rf ~/.cache/go-build/* 2>/dev/null || true
        rm -rf ~/go/pkg/mod/cache/* 2>/dev/null || true
        echo "✅ Cache cleanup completed"

    - name: Install Go dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: go mod download
