name: 'Setup Go'
description: 'Setup Go with caching and dependency installation'
inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25.4'
  install-deps:
    description: 'Whether to install Go dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
      continue-on-error: true

    - name: Install Go dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: go mod download

