[package]
name = "sruja-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared types for Sruja architecture DSL"

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
