[package]
name = "sruja-export"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Exporters for converting Sruja DSL AST to various formats (JSON, Mermaid, Markdown)"

[dependencies]
sruja-diagnostics = { path = "../sruja-diagnostics" }
sruja-language = { path = "../sruja-language" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
sruja-language = { path = "../sruja-language" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
