// pkg/export/svg/javascript.go
// JavaScript generation for interactive features
package svg

import "strings"

func (e *Exporter) writeJavaScript(sb *strings.Builder) {
	sb.WriteString("    <!-- JavaScript -->\n")
	sb.WriteString("    <script type=\"text/ecmascript\">\n")
	sb.WriteString("    <![CDATA[\n")
	sb.WriteString("        let currentView = 'level1';\n")
	sb.WriteString("        let selectedElement = null;\n")
	sb.WriteString("        let scale = 1;\n")
	sb.WriteString("        let panX = 0;\n")
	sb.WriteString("        let panY = 0;\n")
	sb.WriteString("        let isDragging = false;\n")
	sb.WriteString("        let startX = 0;\n")
	sb.WriteString("        let startY = 0;\n\n")
	sb.WriteString("        function loadContent(dataId) {\n")
	sb.WriteString("            const sourceGroup = document.getElementById(dataId);\n")
	sb.WriteString("            const injectionArea = document.getElementById('contentInjection');\n")
	sb.WriteString("            const initialText = document.getElementById('initialText');\n")
	sb.WriteString("            if (!sourceGroup) { console.error('Content ID not found: ' + dataId); return; }\n")
	sb.WriteString("            initialText.style.display = 'none';\n")
	sb.WriteString("            injectionArea.innerHTML = '';\n")
	sb.WriteString("            let yOffset = 0;\n")
	sb.WriteString("            Array.from(sourceGroup.children).forEach(child => {\n")
	sb.WriteString("                const clonedChild = child.cloneNode(true);\n")
	sb.WriteString("                clonedChild.setAttribute('y', yOffset);\n")
	sb.WriteString("                if (clonedChild.classList.contains('section-header')) { yOffset += 50; }\n")
	sb.WriteString("                else if (clonedChild.classList.contains('doc-list-item')) { yOffset += 28; }\n")
	sb.WriteString("                else { yOffset += 35; }\n")
	sb.WriteString("                injectionArea.appendChild(clonedChild);\n")
	sb.WriteString("            });\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function switchView(viewId) {\n")
	sb.WriteString("            // Hide all views\n")
	sb.WriteString("            document.querySelectorAll('#diagramArea > g').forEach(view => {\n")
	sb.WriteString("                view.style.display = 'none';\n")
	sb.WriteString("            });\n")
	sb.WriteString("            // Show the requested view\n")
	sb.WriteString("            const targetView = document.getElementById(viewId === 'level1' ? 'level1' : 'view-' + viewId);\n")
	sb.WriteString("            if (targetView) {\n")
	sb.WriteString("                targetView.style.display = 'block';\n")
	sb.WriteString("                currentView = viewId;\n")
	sb.WriteString("                // Get level from view element's data-level attribute\n")
	sb.WriteString("                const level = parseInt(targetView.getAttribute('data-level')) || 1;\n")
	sb.WriteString("                // Update level button states\n")
	sb.WriteString("                document.querySelectorAll('[data-level]').forEach(btn => {\n")
	sb.WriteString("                    const btnLevel = parseInt(btn.getAttribute('data-level'));\n")
	sb.WriteString("                    if (btnLevel === level) {\n")
	sb.WriteString("                        btn.classList.add('button-active');\n")
	sb.WriteString("                        const textEl = btn.querySelector('.button-text');\n")
	sb.WriteString("                        if (textEl) textEl.classList.add('button-text-active');\n")
	sb.WriteString("                    } else {\n")
	sb.WriteString("                        btn.classList.remove('button-active');\n")
	sb.WriteString("                        const textEl = btn.querySelector('.button-text');\n")
	sb.WriteString("                        if (textEl) textEl.classList.remove('button-text-active');\n")
	sb.WriteString("                    }\n")
	sb.WriteString("                });\n")
	sb.WriteString("            } else {\n")
	sb.WriteString("                console.error('View not found: ' + viewId);\n")
	sb.WriteString("            }\n")
	sb.WriteString("            clearSelection();\n")
	sb.WriteString("            resetZoom();\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function switchLevel(level) {\n")
	sb.WriteString("            if (level === 1) {\n")
	sb.WriteString("                switchView('level1');\n")
	sb.WriteString("            } else {\n")
	sb.WriteString("                // For level 2/3, show the first available view of that level\n")
	sb.WriteString("                const views = document.querySelectorAll('#diagramArea > g[data-level=\"' + level + '\"]');\n")
	sb.WriteString("                if (views.length > 0) {\n")
	sb.WriteString("                    const firstView = views[0];\n")
	sb.WriteString("                    const viewId = firstView.id === 'level1' ? 'level1' : firstView.id.replace('view-', '');\n")
	sb.WriteString("                    switchView(viewId);\n")
	sb.WriteString("                } else {\n")
	sb.WriteString("                    // Fallback to level 1 if no view found for requested level\n")
	sb.WriteString("                    switchView('level1');\n")
	sb.WriteString("                }\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function drillDown(elementId) {\n")
	sb.WriteString("            // Check if there's a view for this element\n")
	sb.WriteString("            const viewEl = document.getElementById('view-' + elementId);\n")
	sb.WriteString("            if (viewEl) {\n")
	sb.WriteString("                switchView(elementId);\n")
	sb.WriteString("            } else {\n")
	sb.WriteString("                console.log('No drill-down view available for: ' + elementId);\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function selectElement(element) {\n")
	sb.WriteString("            clearSelection();\n")
	sb.WriteString("            selectedElement = element;\n")
	sb.WriteString("            element.classList.add('selected');\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function clearSelection() {\n")
	sb.WriteString("            if (selectedElement) { selectedElement.classList.remove('selected'); }\n")
	sb.WriteString("            selectedElement = null;\n")
	sb.WriteString("            document.querySelectorAll('.interactive').forEach(el => el.classList.remove('selected'));\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        // Zoom and Pan\n")
	sb.WriteString("        function updateTransform() {\n")
	sb.WriteString("            const diagramArea = document.getElementById('diagramArea');\n")
	sb.WriteString("            diagramArea.setAttribute('transform', `translate(${panX}, ${panY}) scale(${scale})`);\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function zoomIn() {\n")
	sb.WriteString("            scale *= 1.2;\n")
	sb.WriteString("            updateTransform();\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function zoomOut() {\n")
	sb.WriteString("            scale /= 1.2;\n")
	sb.WriteString("            updateTransform();\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function resetZoom() {\n")
	sb.WriteString("            scale = 1;\n")
	sb.WriteString("            panX = 0;\n")
	sb.WriteString("            panY = 0;\n")
	sb.WriteString("            updateTransform();\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function startDrag(evt) {\n")
	sb.WriteString("            if (evt.target.classList.contains('interactive') || evt.target.closest('.interactive')) return;\n")
	sb.WriteString("            isDragging = true;\n")
	sb.WriteString("            startX = evt.clientX;\n")
	sb.WriteString("            startY = evt.clientY;\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function drag(evt) {\n")
	sb.WriteString("            if (!isDragging) return;\n")
	sb.WriteString("            evt.preventDefault();\n")
	sb.WriteString("            const dx = evt.clientX - startX;\n")
	sb.WriteString("            const dy = evt.clientY - startY;\n")
	sb.WriteString("            panX += dx;\n")
	sb.WriteString("            panY += dy;\n")
	sb.WriteString("            startX = evt.clientX;\n")
	sb.WriteString("            startY = evt.clientY;\n")
	sb.WriteString("            updateTransform();\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function endDrag() {\n")
	sb.WriteString("            isDragging = false;\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        // Search\n")
	sb.WriteString("        function search(query) {\n")
	sb.WriteString("            if (!query) return;\n")
	sb.WriteString("            query = query.toLowerCase();\n")
	sb.WriteString("            const elements = document.querySelectorAll('.interactive');\n")
	sb.WriteString("            let found = false;\n")
	sb.WriteString("            elements.forEach(el => {\n")
	sb.WriteString("                const text = el.textContent.toLowerCase(); // Simple text content search\n")
	sb.WriteString("                // Better: search data-content-id or specific labels\n")
	sb.WriteString("                // For now, let's search the text inside the element group/rect\n")
	sb.WriteString("                // Actually, the rect doesn't have text inside it in DOM structure here, \n")
	sb.WriteString("                // text is sibling. We need a better way to link text to rect for search.\n")
	sb.WriteString("                // But wait, the 'interactive' class is on the rect. The text is separate.\n")
	sb.WriteString("                // We should probably search the data store or the visible text.\n")
	sb.WriteString("                \n")
	sb.WriteString("                // Let's search visible text elements that are siblings of interactive rects?\n")
	sb.WriteString("                // Or just search all text elements and if match, highlight parent/sibling?\n")
	sb.WriteString("                \n")
	sb.WriteString("                // Simpler approach: Iterate all text elements in the current level.\n")
	sb.WriteString("                if (el.nextElementSibling && el.nextElementSibling.textContent.toLowerCase().includes(query)) {\n")
	sb.WriteString("                     selectElement(el);\n")
	sb.WriteString("                     found = true;\n")
	sb.WriteString("                     // Load content if found\n")
	sb.WriteString("                     const dataId = el.getAttribute('data-content-id');\n")
	sb.WriteString("                     if(dataId) loadContent(dataId);\n")
	sb.WriteString("                }\n")
	sb.WriteString("            });\n")
	sb.WriteString("            if (!found) {\n")
	sb.WriteString("                alert('No element found matching: ' + query);\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        function init() {\n")
	sb.WriteString("            document.querySelectorAll('[data-level]').forEach(btn => {\n")
	sb.WriteString("                btn.addEventListener('click', function() {\n")
	sb.WriteString("                    switchLevel(parseInt(this.getAttribute('data-level')));\n")
	sb.WriteString("                });\n")
	sb.WriteString("            });\n")
	sb.WriteString("            document.querySelectorAll('.interactive').forEach(element => {\n")
	sb.WriteString("                const elementId = element.id;\n")
	sb.WriteString("                const dataId = element.getAttribute('data-content-id');\n")
	sb.WriteString("                const drillView = element.getAttribute('data-drill-view');\n")
	sb.WriteString("                if (elementId) {\n")
	sb.WriteString("                    element.addEventListener('click', function(e) {\n")
	sb.WriteString("                        e.stopPropagation();\n")
	sb.WriteString("                        // If drill-down is available, do that first\n")
	sb.WriteString("                        if (drillView) {\n")
	sb.WriteString("                            drillDown(drillView);\n")
	sb.WriteString("                        } else if (document.getElementById('view-' + elementId)) {\n")
	sb.WriteString("                            drillDown(elementId);\n")
	sb.WriteString("                        }\n")
	sb.WriteString("                        // Also load content if available\n")
	sb.WriteString("                        if (dataId) {\n")
	sb.WriteString("                            loadContent(dataId);\n")
	sb.WriteString("                        }\n")
	sb.WriteString("                        selectElement(this);\n")
	sb.WriteString("                    });\n")
	sb.WriteString("                }\n")
	sb.WriteString("            });\n")
	sb.WriteString("            document.querySelectorAll('#quickAccess [data-content-id]').forEach(btn => {\n")
	sb.WriteString("                btn.addEventListener('click', function() {\n")
	sb.WriteString("                    loadContent(this.getAttribute('data-content-id'));\n")
	sb.WriteString("                    clearSelection();\n")
	sb.WriteString("                });\n")
	sb.WriteString("            });\n")
	sb.WriteString("            \n")
	sb.WriteString("            // Zoom/Pan Listeners\n")
	sb.WriteString("            document.addEventListener('mousedown', startDrag);\n")
	sb.WriteString("            document.addEventListener('mousemove', drag);\n")
	sb.WriteString("            document.addEventListener('mouseup', endDrag);\n")
	sb.WriteString("            document.addEventListener('mouseleave', endDrag);\n")
	sb.WriteString("            \n")
	sb.WriteString("            // Zoom Buttons (to be added in UI)\n")
	sb.WriteString("            const btnZoomIn = document.getElementById('btnZoomIn');\n")
	sb.WriteString("            if(btnZoomIn) btnZoomIn.addEventListener('click', zoomIn);\n")
	sb.WriteString("            \n")
	sb.WriteString("            const btnZoomOut = document.getElementById('btnZoomOut');\n")
	sb.WriteString("            if(btnZoomOut) btnZoomOut.addEventListener('click', zoomOut);\n")
	sb.WriteString("            \n")
	sb.WriteString("            const btnReset = document.getElementById('btnReset');\n")
	sb.WriteString("            if(btnReset) btnReset.addEventListener('click', resetZoom);\n\n")
	sb.WriteString("            // Search Input (to be added in UI)\n")
	sb.WriteString("            const searchInput = document.getElementById('searchInput');\n")
	sb.WriteString("            if(searchInput) {\n")
	sb.WriteString("                searchInput.addEventListener('keypress', function(e) {\n")
	sb.WriteString("                    if (e.key === 'Enter') {\n")
	sb.WriteString("                        search(this.value);\n")
	sb.WriteString("                    }\n")
	sb.WriteString("                });\n")
	sb.WriteString("            }\n\n")
	sb.WriteString("            switchLevel(1);\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        if (document.readyState === 'loading') {\n")
	sb.WriteString("            document.addEventListener('DOMContentLoaded', init);\n")
	sb.WriteString("        } else { init(); }\n")
	sb.WriteString("    ]]>\n")
	sb.WriteString("    </script>\n\n")
}
