[package]
name = "sruja-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sruja-diagnostics = { path = "../sruja-diagnostics" }
sruja-language = { path = "../sruja-language" }
sruja-engine = { path = "../sruja-engine" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
async-trait = { workspace = true }
