[package]
name = "sruja-report"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Compliance report schema for Sruja"

[dependencies]
serde = { workspace = true }
sruja-diff = { path = "../sruja-diff" }

[dev-dependencies]
serde_json = { workspace = true }
